-- Расширенный глобальный сид-каталог (см. docs/SPEC.md §3.1).
-- Двуязычный (en/uk), с кластером и категорией. Идемпотентно: ON CONFLICT DO UPDATE
-- по уникальному индексу exercises_global_name_uidx (name_en среди is_global),
-- поэтому миграция и заводит новые, и обновляет ранее засеянные 16 упражнений.

insert into public.exercises
  (name_en, name_uk, muscle_group, equipment, aliases, cluster, category, is_global)
values
  ('Back Squat', 'Присід зі штангою', 'legs', 'barbell', array['squat','back squat','присід','присяд','присід зі штангою'], 'lower', 'general', true),
  ('Front Squat', 'Фронтальний присід', 'legs', 'barbell', array['front squat','фронт','фронтальний присід','фронт присяд'], 'lower', 'general', true),
  ('Overhead Squat', 'Присід над головою', 'legs', 'barbell', array['overhead squat','оверхед присід','присід над головою'], 'full', 'weightlifting', true),
  ('Deadlift', 'Станова тяга', 'back', 'barbell', array['deadlift','станова тяга','станова','тяга'], 'lower', 'general', true),
  ('Sumo Deadlift', 'Сумо станова', 'legs', 'barbell', array['sumo deadlift','сумо','сумо тяга','сумо станова'], 'lower', 'general', true),
  ('Romanian Deadlift', 'Румунська тяга', 'hamstrings', 'barbell', array['rdl','romanian deadlift','румунська','румунська тяга'], 'lower', 'general', true),
  ('Snatch-grip Deadlift', 'Станова ривковим хватом', 'back', 'barbell', array['snatch grip deadlift','ривковим хватом','станова широким хватом'], 'full', 'weightlifting', true),
  ('Hip Thrust', 'Хіп-траст', 'glutes', 'barbell', array['hip thrust','хіп траст','сідничний міст'], 'lower', 'general', true),
  ('Glute Bridge', 'Сідничний місток', 'glutes', 'barbell', array['glute bridge','місток','містки','сідничний місток'], 'lower', 'general', true),
  ('Lunges', 'Випади', 'legs', 'dumbbell', array['lunge','lunges','випади'], 'lower', 'general', true),
  ('Walking Lunge', 'Крокуючі випади', 'legs', 'dumbbell', array['walking lunge','крокуючі випади','випади проходка'], 'lower', 'general', true),
  ('Reverse Lunge', 'Випади назад', 'legs', 'dumbbell', array['reverse lunge','випади назад'], 'lower', 'general', true),
  ('Bulgarian Split Squat', 'Болгарський випад', 'legs', 'dumbbell', array['bulgarian','болгарський випад','болгари'], 'lower', 'general', true),
  ('Step-up on Box', 'Зашаг на ящик', 'legs', 'dumbbell', array['step up','зашаг','зашаги на ящик','зашаг на короб','переходи через ящик'], 'lower', 'general', true),
  ('Pistol Squat', 'Пістолет', 'legs', 'bodyweight', array['pistol','пістолет','пістолєт','пістолєтікі','присід на одній'], 'lower', 'gymnastics', true),
  ('Goblet Squat', 'Гоблет-присід', 'legs', 'kettlebell', array['goblet','гоблет','гоблет присід'], 'lower', 'general', true),
  ('Leg Curl', 'Згинання ніг лежачи', 'hamstrings', 'machine', array['leg curl','згинання ніг','хамстринг'], 'lower', 'general', true),
  ('Bench Press', 'Жим лежачи', 'chest', 'barbell', array['bench','bench press','жим лежачи','жим'], 'upper', 'general', true),
  ('Incline Bench Press', 'Жим лежачи в нахилі', 'chest', 'barbell', array['incline bench','жим в нахилі','жим в наклоне'], 'upper', 'general', true),
  ('Dumbbell Bench Press', 'Жим гантелей лежачи', 'chest', 'dumbbell', array['db bench','жим гантелей грудними','жим гантелей лежачи','жим грудних'], 'upper', 'general', true),
  ('Overhead Press', 'Жим стоячи', 'shoulders', 'barbell', array['ohp','overhead press','жим стоячи','жим плечей','жим плечі'], 'upper', 'general', true),
  ('Seated Shoulder Press', 'Жим сидячи', 'shoulders', 'dumbbell', array['seated press','жим сидячи','жим штанги сидячи'], 'upper', 'general', true),
  ('Dumbbell Shoulder Press', 'Жим гантелей на плечі', 'shoulders', 'dumbbell', array['db shoulder press','жим гантелей плечі'], 'upper', 'general', true),
  ('Barbell Row', 'Тяга штанги в нахилі', 'back', 'barbell', array['barbell row','тяга штанги','тяга до живота','тяга до спини'], 'upper', 'general', true),
  ('Dumbbell Row', 'Тяга гантелі', 'back', 'dumbbell', array['db row','тяга гантелі','тяга гантелі лопаткою','тяга лопаткою'], 'upper', 'general', true),
  ('Gorilla Row', 'Тяга «горила»', 'back', 'kettlebell', array['gorilla row','тяга горілли','тяга горили'], 'upper', 'crossfit', true),
  ('Lat Pulldown', 'Тяга верхнього блоку', 'back', 'machine', array['lat pulldown','тяга верхнього блоку','верхній блок'], 'upper', 'general', true),
  ('Face Pull', 'Тяга до обличчя', 'shoulders', 'cable', array['face pull','тяга до обличчя','тяга резинки до обличчя'], 'upper', 'general', true),
  ('Biceps Curl', 'Згинання на біцепс', 'arms', 'dumbbell', array['biceps curl','біцепс','згинання на біцепс'], 'upper', 'general', true),
  ('Triceps Dip on Bench', 'Зворотні відтискання на трицепс', 'arms', 'bodyweight', array['triceps dip','трицепс','зворотні відтискання','відтискання від лавки'], 'upper', 'general', true),
  ('Pull-up', 'Підтягування', 'back', 'bodyweight', array['pull-up','pullup','підтягування','турнік'], 'upper', 'gymnastics', true),
  ('Assisted Pull-up', 'Підтягування з резинкою', 'back', 'bodyweight', array['assisted pull-up','підтягування з резинкою','підтягування з допомогою'], 'upper', 'gymnastics', true),
  ('Negative Pull-up', 'Негативне підтягування', 'back', 'bodyweight', array['negative pull-up','негативне підтягування','негативи підтягувань'], 'upper', 'gymnastics', true),
  ('Dead Hang', 'Віс на перекладині', 'forearms', 'bodyweight', array['dead hang','віс','утримання в висі','завісання'], 'upper', 'gymnastics', true),
  ('Ring Row', 'Тяга на кільцях', 'back', 'rings', array['ring row','тяга на кільцях','кільця тяга'], 'upper', 'gymnastics', true),
  ('Ring Dip', 'Відтискання на кільцях', 'chest', 'rings', array['ring dip','відтискання на кільцях','кільця'], 'upper', 'gymnastics', true),
  ('Push-up', 'Віджимання', 'chest', 'bodyweight', array['push-up','pushup','віджимання','відтискання'], 'upper', 'gymnastics', true),
  ('Pike Push-up', 'Пайк-відтискання', 'shoulders', 'bodyweight', array['pike push-up','пайк','пайк відтискання'], 'upper', 'gymnastics', true),
  ('Rope Climb', 'Лазіння по канату', 'back', 'bodyweight', array['rope climb','канат','лазіння по канату'], 'upper', 'gymnastics', true),
  ('Wall Walk', 'Заходи на стіну', 'shoulders', 'bodyweight', array['wall walk','заходи на стіну','захід на стіну'], 'full', 'gymnastics', true),
  ('Handstand Hold', 'Стійка на руках', 'shoulders', 'bodyweight', array['handstand','стійка на руках','куточок біля стіни'], 'full', 'gymnastics', true),
  ('Power Snatch', 'Ривок силовий', 'full_body', 'barbell', array['power snatch','ривок','ривок силовий','підрив ривок'], 'full', 'weightlifting', true),
  ('Snatch', 'Ривок штанги', 'full_body', 'barbell', array['snatch','ривок штанги'], 'full', 'weightlifting', true),
  ('Power Clean', 'Взяття на груди силове', 'full_body', 'barbell', array['power clean','взяття на груди','взяття'], 'full', 'weightlifting', true),
  ('Hang Clean', 'Взяття з вису', 'full_body', 'barbell', array['hang clean','взяття з вису','взяття із вису'], 'full', 'weightlifting', true),
  ('Clean and Jerk', 'Поштовх', 'full_body', 'barbell', array['clean and jerk','поштовх','взяття поштовх'], 'full', 'weightlifting', true),
  ('Push Press', 'Швунг жимовий', 'shoulders', 'barbell', array['push press','швунг','швунги'], 'full', 'weightlifting', true),
  ('High Pull', 'Підрив', 'full_body', 'barbell', array['high pull','підрив','протяжка'], 'full', 'weightlifting', true),
  ('Thruster', 'Трастер', 'full_body', 'barbell', array['thruster','трастер','трастери'], 'full', 'crossfit', true),
  ('Burpee', 'Бьорпі', 'full_body', 'bodyweight', array['burpee','бьорпі','берпи','бурпи'], 'full', 'crossfit', true),
  ('Wall Ball', 'Воллбол', 'full_body', 'other', array['wall ball','воллбол','волбол','волболи'], 'full', 'crossfit', true),
  ('Devil Press', 'Девіл-прес', 'full_body', 'dumbbell', array['devil press','девіл прес','девіл-прес'], 'full', 'crossfit', true),
  ('Box Jump', 'Застрибування на ящик', 'legs', 'other', array['box jump','застрибування на ящик','застрибнула на короб'], 'full', 'crossfit', true),
  ('Box Step-over', 'Перешагування ящика', 'legs', 'other', array['box step over','перешагування ящика','перешагувань коробки'], 'full', 'crossfit', true),
  ('Jump Rope', 'Скакалка', 'full_body', 'other', array['jump rope','скакалка','скакалки'], 'full', 'crossfit', true),
  ('Double Unders', 'Подвійні скакалки', 'full_body', 'other', array['double unders','подвійні','дабли'], 'full', 'crossfit', true),
  ('Rowing Erg', 'Гребля (тренажер)', 'full_body', 'machine', array['rowing','гребля','грєбля','гребний тренажер'], 'full', 'crossfit', true),
  ('Assault Bike', 'Ейр-байк', 'full_body', 'machine', array['assault bike','байк','ейр байк','велотренажер'], 'full', 'crossfit', true),
  ('Ski Erg', 'Лижний тренажер', 'full_body', 'machine', array['ski erg','лижі','лижний тренажер'], 'full', 'crossfit', true),
  ('Sit-up', 'Складка (сіт-ап)', 'core', 'bodyweight', array['sit-up','sit up','складка','складки','сетап'], 'core', 'crossfit', true),
  ('Kettlebell Swing', 'Махи гирею', 'full_body', 'kettlebell', array['kb swing','махи гирею','махи гирі','мах'], 'full', 'kettlebell', true),
  ('Kettlebell Snatch', 'Ривок гирі', 'full_body', 'kettlebell', array['kb snatch','ривок гирі'], 'full', 'kettlebell', true),
  ('Kettlebell Clean', 'Взяття гирі', 'full_body', 'kettlebell', array['kb clean','взяття гирі'], 'full', 'kettlebell', true),
  ('Kettlebell Press', 'Жим гирі', 'shoulders', 'kettlebell', array['kb press','жим гирі'], 'upper', 'kettlebell', true),
  ('Kettlebell Push Press', 'Швунг гирі', 'shoulders', 'kettlebell', array['kb push press','швунг гирі','швунги гирі'], 'full', 'kettlebell', true),
  ('Turkish Get-up', 'Турецький підйом', 'full_body', 'kettlebell', array['turkish get-up','турецький підйом','турецькі виходи'], 'full', 'kettlebell', true),
  ('Low Pulley Side Pull', 'Натяжка з нижнього блока', 'forearms', 'cable', array['side pull','low pulley','натяжка','натяжка з нижнього блока'], 'upper', 'armwrestling', true),
  ('Wrist Curl on Strap Handle', 'Кисть на лямках', 'forearms', 'cable', array['wrist curl','кисть','ручка','strap','кисть на лямках'], 'upper', 'armwrestling', true),
  ('Pronation', 'Пронація', 'forearms', 'cable', array['pronation','пронація'], 'upper', 'armwrestling', true),
  ('Movement Imitation', 'Імітація руху', 'arms', 'cable', array['imitation','імітація','імітація руху','борьба'], 'upper', 'armwrestling', true),
  ('Plate Pinch', 'Хват млинця', 'forearms', 'other', array['plate pinch','хват млинця','перехват млинця','тримання млинця','щипок'], 'upper', 'armwrestling', true),
  ('Wrist Roller', 'Кистьовий ролик', 'forearms', 'other', array['wrist roller','кистьовий ролик','ролик на хват'], 'upper', 'armwrestling', true),
  ('Farmer''s Carry', 'Прогулянка фермера', 'forearms', 'dumbbell', array['farmers carry','фермера','прогулянка фермера','перенос ваги'], 'full', 'general', true),
  ('Plank', 'Планка', 'core', 'bodyweight', array['plank','планка'], 'core', 'general', true),
  ('Side Plank', 'Бічна планка', 'core', 'bodyweight', array['side plank','бічна планка'], 'core', 'general', true),
  ('Hollow Hold', 'Холлоу', 'core', 'bodyweight', array['hollow','холлоу','порожнисте тіло'], 'core', 'gymnastics', true),
  ('L-sit', 'Куточок', 'core', 'bodyweight', array['l-sit','куточок','кутик'], 'core', 'gymnastics', true),
  ('Toes-to-Bar', 'Носки до перекладини', 'core', 'bodyweight', array['toes to bar','носки до перекладини','носкі до турніка'], 'core', 'gymnastics', true),
  ('Toes-to-Rings', 'Носки до кілець', 'core', 'rings', array['toes to rings','носки до кілець','носкі до кілець'], 'core', 'gymnastics', true),
  ('Hanging Leg Raise', 'Підйом ніг у висі', 'core', 'bodyweight', array['hanging leg raise','підйом ніг у висі'], 'core', 'gymnastics', true),
  ('Crunch', 'Скручування', 'core', 'bodyweight', array['crunch','скручування'], 'core', 'general', true),
  ('Russian Twist', 'Російські скручування', 'core', 'bodyweight', array['russian twist','російські скручування','скручування з поворотом'], 'core', 'general', true)
on conflict (name_en) where is_global do update set
  name_uk      = excluded.name_uk,
  muscle_group = excluded.muscle_group,
  equipment    = excluded.equipment,
  aliases      = excluded.aliases,
  cluster      = excluded.cluster,
  category     = excluded.category;
